name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test-01:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "01"
  build-and-test-02:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "02"
  build-and-test-03:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "03"
  build-and-test-04:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "04"
  build-and-test-05:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "05"
  build-and-test-06:
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      dir: "06"
